### ISSUE TITLE
Non GPL License possible?

### ISSUE THREAD

**Issue by chafey** [rii-mango/JPEGLosslessDecoderJS#1]
Hello,

Congratulations on this great effort!  I would love to add this to the cornerstone project which is licensed under MIT - would it be possible to dual license this library so there is no conflict?

Chris

**Comment by fernandojsg** [comment]
:+1: for this request

**Comment by rii-mango** [comment]
The license is LGPL, not GPL.  I am not the original author (see [Acknowledgements](https://github.com/rii-mango/JPEGLosslessDecoderJS#acknowledgments)).  I made significant modifications, but that isn't enough to change the license, as far as I know.

But my understanding is that a LGPL library is compatible with a MIT project.  The main restriction is that the MIT project must be designed to "work with" the library without it being simply merged into the project.  With JavaScript, what exactly LGPL means is a little fuzzy, since there's no way to compile a stand-alone library and no concept of "linking" to it.  

My take has been to configure it as a dependency: see [Daikon](https://github.com/rii-mango/Daikon/) which is BSD (similar to MIT) license.  Its GitHub project doesn't contain the JPEGLosselessDecoderJS code, rather it's a [dependency](https://github.com/rii-mango/Daikon/blob/master/package.json) and NPM installs it.

I would be happy to re-license it as MIT, if I could -- but my understanding is that I can't.  My preference is BSD/MIT whenever possible.

**Comment by chafey** [comment]
Understood - this will unfortunately limit how much use this library gets as many commercial companies prohibit use of GPL and LGPL software in their products.  I think the best strategy for cornerstone is to make it so use of this library is optional so it can be excluded by those that can't use LGPL or don't need it.  One thing that would help is to publish this library via bower - would that be possible?  I am thinking of switching everything over to NPM in the future, but right now bower is what is being used.

**Comment by rii-mango** [comment]
I've sent the original author an email asking if he'd be willing to allow a license change.  Either way, I'll look into adding Bower support...

**Comment by chafey** [comment]
OK great - would you like me to submit a PR with instructions for bower?

**Comment by rii-mango** [comment]
Yes, that would be great.

**Comment by rii-mango** [comment]
The original author approved the change in license from LGPL to MIT.  I'll make this change as well as the other requests sometime this week...

**Comment by chafey** [comment]
Great news!  Thank you for looking into this!

**Comment by chafey** [comment]
Just submitted a PR with bower support.  If you don't want to mess with bower, I can just bundle it in with cornerstone since you are going to support MIT.  Let me know

**Comment by fernandojsg** [comment]
That's a really great news! Thank you too

**Comment by rii-mango** [comment]
License has been changed.
