### ISSUE TITLE
Problem showing image properly

### ISSUE THREAD

**Issue by idmpacs** [rii-mango/JPEGLosslessDecoderJS#8]
I have problem showing below DICOM image properly
[1.2.826.0.1.3680043.6.12976.22475.20080618123810.264.6403.zip](https://github.com/rii-mango/JPEGLosslessDecoderJS/files/133759/1.2.826.0.1.3680043.6.12976.22475.20080618123810.264.6403.zip)

Original image
![original](https://cloud.githubusercontent.com/assets/12911306/13101195/60b080ba-d56a-11e5-88b1-894f79f12a06.png)

Decoded using JPEGLosslessDecoderJS
![comp 57](https://cloud.githubusercontent.com/assets/12911306/13101213/81c6afa4-d56a-11e5-8dcd-8e353580a099.png)

**Comment by rii-mango** [comment]
The image you linked to isn't compressed.  (It's a normal, uncompressed transfer syntax, highlighted below.)  Do you have another version?

<img width="391" alt="screen shot 2016-02-18 at 2 19 03 pm" src="https://cloud.githubusercontent.com/assets/1859709/13156933/b3806edc-d64a-11e5-9139-67ebf7961670.png">

**Comment by idmpacs** [comment]
Here it is
[JPEG Lossless.zip](https://github.com/rii-mango/JPEGLosslessDecoderJS/files/137366/JPEG.Lossless.zip)

**Comment by rii-mango** [comment]
In this case, it looks like the problem is with the image.  It has an incorrect tag value at (0028,0006).  That is, Planar Configuration is set as 1, but should be 0.  If you notice it loading correctly somewhere, then it may be the case that that viewer is ignoring that tag.  I can verify that it displays strangely just like your screenshot in other viewers (e.g., Osirix).

![screen shot 2016-02-22 at 9 54 19 am](https://cloud.githubusercontent.com/assets/1859709/13223650/bf9cde64-d94a-11e5-9168-082093bf7b38.png)
